"""added marital status

Revision ID: 5dd33083e6c0
Revises: e65467592e16
Create Date: 2021-02-04 00:35:46.012255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd33083e6c0'
down_revision = 'e65467592e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_member', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
        batch_op.alter_column('marital_status',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
        batch_op.alter_column('occupation_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_member', schema=None) as batch_op:
        batch_op.alter_column('occupation_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('marital_status',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)

    # ### end Alembic commands ###
