"""create tables

Revision ID: e65467592e16
Revises: 
Create Date: 2021-02-02 17:21:47.066142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65467592e16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('HDB', 'Condominium', 'Landed', name='housing_types'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female'), nullable=True),
    sa.Column('marital_status', sa.Enum('Single', 'Married'), nullable=True),
    sa.Column('spouse_name', sa.String(length=100), nullable=True),
    sa.Column('occupation_type', sa.Enum('Unemployed', 'Student', 'Employed'), nullable=True),
    sa.Column('annual_income', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('family_member')
    op.drop_table('household')
    # ### end Alembic commands ###
